version: "3.7"

services:
  app:
    image: ghcr.io/peliseev/shorturl-go-app:master
    ports:
      - 80:80
    networks:
      - app-network
    volumes:
      - ${PWD}/.env:/etc/.env

  mongo:
    image: mongo:5.0.8
    volumes:
      - ~/shorturl/mongo/mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shorturl
    networks:
      - app-network

networks:
  app-network:
    driver: bridge